rn-versions/rn-versions.github.io

src/HistoryReader.ts
src/PackageDescription.ts
src/VersionDownloadChart.tsx

This reworks point sorting to allow better handling of canaries, more granular oredering, and more consistent language between components.
Before:
After:

Rework Point Sorting

---

src/PackageCard.tsx
src/VersionDownloadChart.tsx

This adds better logic for determining date ranges to show, to not give a misleading representation of data. Instead of tweaking version count by release channel, we manipulate the time window, to achieve the given resolution we want.
Before:
After:

Filter date range to "popular versions" crteria

---

src/components/VersionDownloadChart.tsx
src/styles/VersionDownloadChart.styles.ts

Currently values on the download count axis varies from hundreds to millions, also printing the whole number reduces the space for the chart itself.
This PR adds custom tick formatter for the download count axis, which aims to shorten the labels and also hides `0` for the clarity.
I have also removed the fixed axis widths, to allow ResoponsiveContainer to calculate those according to the content width. This also results in increased chart area in tile.

format download count, allow axis autosizing

---

src/components/VersionTooltip.tsx

Currently the total value of downloads per data chunk is not visible anywhere, so I thought that adding this to the tooltip could be a nice addition.
This PR adds one more row ate the end on the tooltip which includes the sum for a given data chunk. I thought about disabling it in percentage mode, but finally I leave it in. Feel free to change that I you have a stron opinion on that.

add total value to the chart tooltips

---

scripts/updateHistory.ts

I was just looking into the files (usual procrastination lol) and found out that the JSON data are named as ,json instead of .json.

Fix `,json` typo

---

src/PackageDescription.ts

We don't actually need to apply any custom labels for Expo pre-release versions at the moment. We may revisit this in the future when we adopt a nightly schedule.

Remove Expo prerelease version labeler

---

src/components/VersionTooltip.tsx
src/styles/VersionDownloadChart.styles.ts
src/styles/VersionTooltip.module.scss

:warning: Alert: Subjective change! It's fine if you don't like it. 😉 
Currently IMO the tooltips lacks a bit of clarity, mainly due to the color indicator at the beginning of entry and a bit cramped visually data.
This PR aims to improve the clarity/readability by removing the indicator, applying the color to the version name (since colors are already calculated in a way which ensures good contrast) and adjusting the spacing in and size of the Tooltip container.
I have also centered the date, because I feel like this match the centered headings of the tiles.
There was an attempt to color the values instead of the labels, but due to font weight it looks better and maintains the readability better on the labels. Coloring both parts also feels like too much of the color, it was hard to …

tweak the chart tooltip appearance

---

src/components/PackageCard.tsx
src/components/VersionDownloadChart.tsx

See #25
The current methods of determining popularity is to sum, then rank, all polled download rates over the full window where a chart shows versions. This effectively tries to show the versions with the most area throughout the entire chart.
When we release a new version, we're more interested in what happens in a recent time-period, e.g. the most recent week, as npm is able to most granularly measure.
This biasing doesn't work well for prerelease versions, which may not have downloads for more than a couple of days to use as ranking, but the approach of ranking based on most recent polling will show what we want for longer-lived versions, such as new major releases.
0.68 shows up after this change, though there's still a data spike issue.

Change how popular major versions determined

---

src/global.d.ts
src/react-app-env.d.ts
tsconfig.json

- Cleans up leftovers from react-scripts
- Teaches TypeScript how to deal with SCSS modules - and thus, fixes errors thrown by TypeScript when importing one
- Simplifies and modernizes config
- target is irrelevant, as it's Vite that handles the compilation. So it's best to have it set to esnext to avoid imaginary problems.
- allowJs is not needed, because there's no JS. Yay!
- added noImplicitAny and strictNullChecks for even more strictness. So far so good.
After this change, running `yarn tsc --noEmit` can, separately or as a CI step, validate our code.

Cleanup TypeScript config

---

index.html

Previously fonts _started_ loading only after JS has been downloaded and evaluated. And there's _still_ quite a lot of JS. This caused text on page to render with fallback font first, then jump to Segoe UI. After this change, of course, there's still chance that the fonts won't get there in time for the initial render, but they _will_ load faster, potentially before first render, reducing CLS.
| Waterfall before | Waterfall after | 
| --- | --- |
| <img width="723" alt="image" src="https://github.com/rn-versions/rn-versions.github.io/assets/5426427/6f825bf2-2081-44fd-abd1-8cc53986d124"> | <img width="723" alt="image" src="https://github.com/rn-versions/rn-versions.github.io/assets/5426427/e877cb6e-688d-4b69-8d08-f23cf5a1c56d"> |

Preload fonts from static2.sharepointonline.com

---

src/components/App.tsx
src/components/PackageCard.tsx
src/index.tsx

Now that since #44 we're using correct @types/react(-dom) version, we can get rid of `react-dom/experimental` imports.

Remove react-dom/experimental imports

---

package.json
src/global.d.ts
src/react-app-env.d.ts
tsconfig.json

Now that we cleared TypeScript errors in #33, we can actually run `tsc` and get exit 0. We have also added Prettier command in #36. So, we can now lint, format, and type check our code. So, we can have `test` command that does all of that stuff. Next stop - CI!

Add test command

---

.github/workflows/deploy.yml
.github/workflows/update-history.yml

On the first CI run, it won't have any effect (a negative one, if any, even). On the subsequent runs however, we should see installation time falling drastically.

Add Yarn cache to speed up CI/CD

---

package.json
yarn.lock

As chalk is now native TypeScript, @types/chalk was also removed.

Bump chalk from 4.1.2 to 5.3.0

---

package.json
yarn.lock

As Node 18 is the latest LTS (still), and all our CI and CD runs on Node 18, the only reasonable option for @types/node is version 18.

Bump @types/node from 12.0.0 to 18.0.0

---

package.json
yarn.lock

This package would fail if TypeScript was updated to 5.x.

Bump axios-retry from 3.2.3 to 3.7.0

---

src/PackageDescription.ts

Turns out expo once released 0.1.0pre and 0.1.0pre2, which are not valid semver. Parsing historical data for these causes a crash.

Filter out bad expo version numbers

---

scripts/generateAssets.ts
scripts/updateHistory.ts

Kind of an edge case, but:  if path contained spaces, `__dirname` had `%20`s in its value, unescaped, causing trouble.

Fix JSON written in wrong paths if path contains spaces

---

scripts/generateAssets.ts

In case `versionCounts` are stored as an array (an optimization that landed in #40), we then read the array by skipping all array items with `-1`s. While this is already more optimal than an object in many cases, I've noticed that we could just trim trailing chains of `-1`s in this array, not only reducing the amount of data, but also making it faster to parse. Not a huge win, but it's there, so why not take it?
generated_assets directory size
before: 3 840 513 B
after: 3 707 218 B (-3.5%)

Trim trailing `-1`s when generating assets

---

.github/workflows/ci.yml

In Yarn 4, by default, global cache is utilized, as opposed to `.yarn/cache` directory in repository root in Yarn 2 and 3.

Update Yarn cache location in GitHub Actions

---

src/HistoryReader.ts
src/PackageDescription.ts
src/generated_assets/@callstack_react-native-visionos.json

Closes #74 
Added tracking for `react-native-visionos`.

Add tracking for react-native-visionos
